language: python

python:
  - "3.8"

services:
  - postgresql

addons:
  postgresql: "10.2"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres

install:
  - pip3 install -r requirements.txt

script:
  - pytest test.py
  - pytest --cov=app tests/
  - coverage run -m pytest
 
after_success:
  - coveralls
  - coverage report -m