language: python

python:
  - "3.8"

services:
  - postgresql

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install pytest

before_script:
  - psql -c 'create database StackOverflow_test;' -U postgres

script:
 - pytest
 - coverage run -m pytest
 
after_success:
- coveralls
- coverage report -m