language: python

python:
  - "3.8"

services:
  - postgresql

install:
  - pip3 install -r requirements.txt
  - pip3 install coverage
  - pip3 install coveralls
  - pip3 install pytest
  - pip3 install pytest-cov

script:
 - pytest --cov=app tests/
 - coverage run -m pytest
 
after_success:
- coveralls
- coverage report -m