language: python

python:
  - "3.8"

services:
  - postgresql

install:
  - pip3 install -r requirements.txt
  - pip install coverage
  - pip3 install coveralls
  - pip install pytest

script:
 - pytest
 - coverage run -m pytest
 
after_success:
- coveralls
- coverage report -m